name: Build Standalone app

on: push
#  push:
#    branches: [ master ]
#    tags: [ 'v*.*.*' ]
#
#   Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # no ubuntu-latest atm
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      # configure Next.js cache
      - uses: actions/cache@v3
        name: Cache Next.js bits
        with:
          path: ${{ github.workspace }}/packages/web-ui/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('packages/web-ui/yarn.lock', 'packages/engine/yarn.lock') }}-${{ hashFiles('packages/engine/src/**/*.ts', 'packages/web-ui/**/*.[tj]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('packages/web-ui/yarn.lock', 'packages/engine/yarn.lock') }}-

      - run: yarn
      - name: Build & Release Electron app
        # uses: samuelmeuli/action-electron-builder@v1 - unmaintained, using a fork
        uses: coparse-inc/action-electron-builder@v1.0.0
        with:
          package_root: packages/electron
          build_script_name: build:ci
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}